# Generated by Django 5.2 on 2025-09-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_setting_address_alter_setting_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='setting',
            name='address2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
