# Generated by Django 5.2 on 2025-09-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_address_setting_address1_setting_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
