# Generated by Django 5.2 on 2025-09-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_setting_mobile_alter_setting_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='pinterest',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='twitter',
        ),
    ]
