# Generated by Django 5.2 on 2025-09-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_setting_pinterest_remove_setting_twitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='logo',
            new_name='footer_logo',
        ),
        migrations.AddField(
            model_name='setting',
            name='header_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
