# Generated by Django 5.2 on 2025-09-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_logo_setting_footer_logo_setting_header_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='footer_logo',
            new_name='fotter_logo',
        ),
    ]
