# Generated by Django 5.2 on 2025-09-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('interest', models.CharField(choices=[('products', 'Products'), ('services', 'Services'), ('support', 'Support'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
