# Generated by Django 5.2 on 2025-11-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='herosection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=300, verbose_name='Subtitle')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='contact_hero_images/', verbose_name='Background Image')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
    ]
