# Generated by Django 5.2 on 2025-11-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_herosection'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='hero_bg_color',
            field=models.CharField(default='#1e3c72', max_length=20, verbose_name='Hero Section Background Color'),
        ),
    ]
