# Generated by Django 5.2 on 2025-11-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_herosection_hero_bg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='hero_bg_color',
            field=models.CharField(max_length=20, verbose_name='Hero Section Background Color'),
        ),
    ]
