# Generated by Django 5.2 on 2025-09-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_left', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('image_right', models.ImageField(blank=True, null=True, upload_to='homepage/')),
            ],
        ),
    ]
