# Generated by Django 5.2 on 2025-09-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_title',
        ),
    ]
