# Generated by Django 5.2 on 2025-11-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='hero_text',
            field=models.TextField(default=1, verbose_name='Hero Text'),
            preserve_default=False,
        ),
    ]
