# Generated by Django 5.2 on 2025-11-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutpage_hero_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_photo',
            field=models.ImageField(blank=True, null=True, upload_to='about_hero_photos/', verbose_name='Hero Photo'),
        ),
    ]
