# Generated by Django 5.2 on 2025-11-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_aboutpage_hero_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='hero_bg_color',
            field=models.CharField(default=1, max_length=20, verbose_name='Hero Section Background Color'),
            preserve_default=False,
        ),
    ]
