# Generated by Django 5.2 on 2025-08-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brands_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Brands',
        ),
    ]
