# Generated by Django 5.2 on 2025-09-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_parentcategory_alter_category_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentcategorytranslation',
            name='description',
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parent_categories/'),
        ),
    ]
