# Generated by Django 5.2 on 2025-09-20 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_parentcategorytranslation_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ParentCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.parentcategory'),
            preserve_default=False,
        ),
    ]
