# Generated by Django 5.2 on 2025-09-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_parentcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='ParentCategory',
            new_name='parent_category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ManyToManyField(related_name='categories', to='products.parentcategory'),
        ),
    ]
