# Generated by Django 5.2 on 2025-10-21 15:57

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_parentcategory_products_parent_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Product Page',
                'verbose_name_plural': 'Product Pages',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductpageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('hero_title', models.CharField(max_length=200, verbose_name='Hero Title')),
                ('hero_subtitle', models.CharField(max_length=300, verbose_name='Hero Subtitle')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero_images/', verbose_name='Hero Image')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.productpage')),
            ],
            options={
                'verbose_name': 'Product Page Translation',
                'db_table': 'products_productpage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
