# Generated by Django 5.2 on 2025-11-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productpage_productpagetranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='products/pdf/'),
        ),
    ]
